### PR TITLE
Automatic reverse relationships + external linking

### PR DESCRIPTION
**Pull request by SteinHeselmans**
- automatic creation of reverse relationships (e.g. validates --> validated_by)
- optional displaying of all relationships (including the automatic reverse ones) on every item) --> solves issue 19
- added possibility for having a relationship-kind linking to external hyperlinks
- these external hyperlinks can also appear on item-matrix (for cross referencing)
- sadly I had to give up the templated rendering, maybe ociu knows how to re-enable it on nodes-level? Or you can template the rendering through the css of your stylesheet?

### CODE REVIEW

**Comment by SteinHeselmans** [comment]
I adapted the example to include some changes, and a basic test. But i didn't find out how to run the automatic tests. These might need adaptions as well... How do i run the tests locally?

**Comment by SteinHeselmans** [comment]
Could we progress on this one? @ociu

**Comment by fkromer** [comment]
The possibility to integration with external tools is a great idea. But external hyperlinking is limited very much. What do you think about to separate this part of the pull request into another pull request/issue to discuss possible alternatives?

**Comment by SteinHeselmans** [comment]
i developed them together, and don't know if it is easy to pull the two apart. I can have a try, but don't know when i will have time :disappointed: I understand your question, and also understand it is a big blob to review however...

**Comment by fkromer** [comment]
I will run the pull request on the [autodoc test documentation](https://github.com/ociu/sphinx-traceability-extension/tree/master/tests/docs/autodoc) and try to add some good case examples. If you provide some info about how the bad case situations (~ExtensionError) are observable I can try to add according test cases/examples as well.

**Comment by fkromer** [comment]
@SteinHeselmans @ociu Why no merge? I am cleaning up my github repos and I am going to delete my fork including the related #18 which I would close then.

**Comment by SteinHeselmans** [comment]
I don't know if @ociu  is still active on this project. As my company is using this plugin very extensively and we needed more features, we decided to keep development on our Melexis fork, and not wait for @ociu to merge and release. In the mean time the Melexis fork of this tool has been improved and used a lot by our local community. All of our changes and improvements have been contributed to the Melexis fork... The diff is probably impossible to review by now

**Comment by fkromer** [comment]
@SteinHeselmans Thank's for letting me know.  I will close #18 as well.

**Pull request closed without merging**
